// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class constants
{
        public const string achievement_20000_enemy_points = "CgkI-I2pkfweEAIQGA"; // <GPGSID>
        public const string achievement_3000_enemy_points = "CgkI-I2pkfweEAIQFA"; // <GPGSID>
        public const string achievement_collect_200_items = "CgkI-I2pkfweEAIQEA"; // <GPGSID>
        public const string achievement_4000_enemy_points = "CgkI-I2pkfweEAIQFQ"; // <GPGSID>
        public const string achievement_collect_50_items = "CgkI-I2pkfweEAIQDg"; // <GPGSID>
        public const string achievement_5000_points = "CgkI-I2pkfweEAIQBg"; // <GPGSID>
        public const string achievement_collect_20_items = "CgkI-I2pkfweEAIQCw"; // <GPGSID>
        public const string achievement_1000_points = "CgkI-I2pkfweEAIQAg"; // <GPGSID>
        public const string achievement_2000_enemy_points = "CgkI-I2pkfweEAIQEw"; // <GPGSID>
        public const string achievement_10000_points = "CgkI-I2pkfweEAIQBw"; // <GPGSID>
        public const string achievement_500_points = "CgkI-I2pkfweEAIQAQ"; // <GPGSID>
        public const string achievement_collect_5_items = "CgkI-I2pkfweEAIQCQ"; // <GPGSID>
        public const string leaderboard_normal_mode = "CgkI-I2pkfweEAIQGQ"; // <GPGSID>
        public const string achievement_500_enemy_points = "CgkI-I2pkfweEAIQEQ"; // <GPGSID>
        public const string achievement_20000_points = "CgkI-I2pkfweEAIQCA"; // <GPGSID>
        public const string leaderboard_enemy_mode = "CgkI-I2pkfweEAIQGw"; // <GPGSID>
        public const string leaderboard_item_mode = "CgkI-I2pkfweEAIQGg"; // <GPGSID>
        public const string achievement_10000_enemy_points = "CgkI-I2pkfweEAIQFw"; // <GPGSID>
        public const string achievement_3000_points = "CgkI-I2pkfweEAIQBA"; // <GPGSID>
        public const string achievement_collect_100_items = "CgkI-I2pkfweEAIQDw"; // <GPGSID>
        public const string achievement_4000_points = "CgkI-I2pkfweEAIQBQ"; // <GPGSID>
        public const string achievement_1000_enemy_points = "CgkI-I2pkfweEAIQEg"; // <GPGSID>
        public const string achievement_collect_40_items = "CgkI-I2pkfweEAIQDQ"; // <GPGSID>
        public const string achievement_collect_10_items = "CgkI-I2pkfweEAIQCg"; // <GPGSID>
        public const string achievement_5000_enemy_points = "CgkI-I2pkfweEAIQFg"; // <GPGSID>
        public const string achievement_2000_points = "CgkI-I2pkfweEAIQAw"; // <GPGSID>
        public const string achievement_collect_30_items = "CgkI-I2pkfweEAIQDA"; // <GPGSID>

}

